import "../../src/components/button/sp-button";
import type { Meta, StoryObj } from "@storybook/web-components";
import "@sp-design/token/lib/speeda-tokens.css";
import { speedaIconTypes } from "../../src/components/icon/icons";
import { action } from "@storybook/addon-actions";
import { html } from "lit";

const meta: Meta = {
  component: "sp-button",
  argTypes: {
    text: { type: "string" },
    icon: {
      control: { type: "select" },
      options: ["", ...speedaIconTypes],
    },
    type: {
      control: { type: "select" },
      options: ["default", "destructive"],
    },
    appearance: {
      control: { type: "select" },
      options: ["outline", "fill", "text"],
    },
    size: {
      control: { type: "select" },
      options: ["medium", "large", "xLarge", "width160", "width80"],
    },
    loading: { type: "boolean" },
    selected: { type: "boolean" },
    disabled: { type: "boolean" },
    onclick: {
      action: "onclick",
    },
  },
  args: {
    text: "sp-button-text",
    icon: "",
    type: "default",
    appearance: "fill",
    size: "medium",
    loading: false,
    selected: false,
    disabled: false,
    onclick: action("onclick"),
  },
};
export default meta;

type Story = StoryObj;

export const Basic: Story = {
  args: {
    icon: undefined,
    type: undefined,
    appearance: undefined,
    size: undefined,
    loading: undefined,
    selected: undefined,
    disabled: undefined,
  },
};

export const Property: Story = {};

export const Attribute: Story = {
  render: (args) =>
    html`<sp-button
      text=${args.text}
      icon=${args.icon}
      type=${args.type}
      appearance=${args.appearance}
      size=${args.size}
      loading=${args.loading}
      selected=${args.selected}
      disabled=${args.disabled}
    ></sp-button>`,
};

export const AttributeHTML: Story = {
  render: (args) =>
    html`<sp-button
      text=${args.text}
      icon=${args.icon}
      type=${args.type}
      appearance=${args.appearance}
      size=${args.size}
      ?loading=${args.loading}
      ?selected=${args.selected}
      ?disabled=${args.disabled}
    ></sp-button>`,
};

export const ALL: Story = {
  render: () => html`
    <table>
      <caption>
        size: medium / type: default / icon: edit
      </caption>
      <thead>
        <tr>
          <th>appearance</th>
          <th>outline</th>
          <th>fill</th>
          <th>text</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>state: default</th>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="default"
              icon="edit"
              appearance="outline"
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="default"
              icon="edit"
              appearance="fill"
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="default"
              icon="edit"
              appearance="text"
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: selected</th>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="default"
              icon="edit"
              appearance="outline"
              selected
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="default"
              icon="edit"
              appearance="fill"
              selected
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="default"
              icon="edit"
              appearance="text"
              selected
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: disabled</th>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="default"
              icon="edit"
              appearance="outline"
              disabled
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="default"
              icon="edit"
              appearance="fill"
              disabled
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="default"
              icon="edit"
              appearance="text"
              disabled
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: loading</th>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="default"
              icon="edit"
              appearance="outline"
              loading
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="default"
              icon="edit"
              appearance="fill"
              loading
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="default"
              icon="edit"
              appearance="text"
              loading
            ></sp-button>
          </td>
        </tr>
      </tbody>
    </table>
    <table>
      <caption>
        size: large / type: default / icon: edit
      </caption>
      <thead>
        <tr>
          <th>appearance</th>
          <th>outline</th>
          <th>fill</th>
          <th>text</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>state: default</th>
          <td>
            <sp-button
              text="text"
              size="large"
              type="default"
              icon="edit"
              appearance="outline"
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="large"
              type="default"
              icon="edit"
              appearance="fill"
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="large"
              type="default"
              icon="edit"
              appearance="text"
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: selected</th>
          <td>
            <sp-button
              text="text"
              size="large"
              type="default"
              icon="edit"
              appearance="outline"
              selected
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="large"
              type="default"
              icon="edit"
              appearance="fill"
              selected
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="large"
              type="default"
              icon="edit"
              appearance="text"
              selected
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: disabled</th>
          <td>
            <sp-button
              text="text"
              size="large"
              type="default"
              icon="edit"
              appearance="outline"
              disabled
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="large"
              type="default"
              icon="edit"
              appearance="fill"
              disabled
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="large"
              type="default"
              icon="edit"
              appearance="text"
              disabled
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: loading</th>
          <td>
            <sp-button
              text="text"
              size="large"
              type="default"
              icon="edit"
              appearance="outline"
              loading
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="large"
              type="default"
              icon="edit"
              appearance="fill"
              loading
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="large"
              type="default"
              icon="edit"
              appearance="text"
              loading
            ></sp-button>
          </td>
        </tr>
      </tbody>
    </table>
    <table>
      <caption>
        size: xLarge / type: default / icon: edit
      </caption>
      <thead>
        <tr>
          <th>appearance</th>
          <th>outline</th>
          <th>fill</th>
          <th>text</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>state: default</th>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="default"
              icon="edit"
              appearance="outline"
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="default"
              icon="edit"
              appearance="fill"
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="default"
              icon="edit"
              appearance="text"
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: selected</th>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="default"
              icon="edit"
              appearance="outline"
              selected
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="default"
              icon="edit"
              appearance="fill"
              selected
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="default"
              icon="edit"
              appearance="text"
              selected
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: disabled</th>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="default"
              icon="edit"
              appearance="outline"
              disabled
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="default"
              icon="edit"
              appearance="fill"
              disabled
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="default"
              icon="edit"
              appearance="text"
              disabled
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: loading</th>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="default"
              icon="edit"
              appearance="outline"
              loading
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="default"
              icon="edit"
              appearance="fill"
              loading
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="default"
              icon="edit"
              appearance="text"
              loading
            ></sp-button>
          </td>
        </tr>
      </tbody>
    </table>
    <table>
      <caption>
        size: width80 / type: default / icon: edit
      </caption>
      <thead>
        <tr>
          <th>appearance</th>
          <th>outline</th>
          <th>fill</th>
          <th>text</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>state: default</th>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="default"
              icon="edit"
              appearance="outline"
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="default"
              icon="edit"
              appearance="fill"
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="default"
              icon="edit"
              appearance="text"
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: selected</th>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="default"
              icon="edit"
              appearance="outline"
              selected
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="default"
              icon="edit"
              appearance="fill"
              selected
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="default"
              icon="edit"
              appearance="text"
              selected
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: disabled</th>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="default"
              icon="edit"
              appearance="outline"
              disabled
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="default"
              icon="edit"
              appearance="fill"
              disabled
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="default"
              icon="edit"
              appearance="text"
              disabled
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: loading</th>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="default"
              icon="edit"
              appearance="outline"
              loading
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="default"
              icon="edit"
              appearance="fill"
              loading
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="default"
              icon="edit"
              appearance="text"
              loading
            ></sp-button>
          </td>
        </tr>
      </tbody>
    </table>
    <table>
      <caption>
        size: width160 / type: default / icon: edit
      </caption>
      <thead>
        <tr>
          <th>appearance</th>
          <th>outline</th>
          <th>fill</th>
          <th>text</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>state: default</th>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="default"
              icon="edit"
              appearance="outline"
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="default"
              icon="edit"
              appearance="fill"
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="default"
              icon="edit"
              appearance="text"
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: selected</th>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="default"
              icon="edit"
              appearance="outline"
              selected
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="default"
              icon="edit"
              appearance="fill"
              selected
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="default"
              icon="edit"
              appearance="text"
              selected
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: disabled</th>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="default"
              icon="edit"
              appearance="outline"
              disabled
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="default"
              icon="edit"
              appearance="fill"
              disabled
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="default"
              icon="edit"
              appearance="text"
              disabled
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: loading</th>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="default"
              icon="edit"
              appearance="outline"
              loading
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="default"
              icon="edit"
              appearance="fill"
              loading
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="default"
              icon="edit"
              appearance="text"
              loading
            ></sp-button>
          </td>
        </tr>
      </tbody>
    </table>
    <table>
      <caption>
        size: medium / type: destructive / icon: edit
      </caption>
      <thead>
        <tr>
          <th>appearance</th>
          <th>outline</th>
          <th>fill</th>
          <th>text</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>state: default</th>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="destructive"
              icon="edit"
              appearance="outline"
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="destructive"
              icon="edit"
              appearance="fill"
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="destructive"
              icon="edit"
              appearance="text"
            ></sp-button>
          </td>
        </tr>
        <tr style="background: #ccc">
          <th>state: selected</th>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="destructive"
              icon="edit"
              appearance="outline"
              selected
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="destructive"
              icon="edit"
              appearance="fill"
              selected
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="destructive"
              icon="edit"
              appearance="text"
              selected
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: disabled</th>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="destructive"
              icon="edit"
              appearance="outline"
              disabled
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="destructive"
              icon="edit"
              appearance="fill"
              disabled
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="destructive"
              icon="edit"
              appearance="text"
              disabled
            ></sp-button>
          </td>
        </tr>
        <tr style="background: #ccc">
          <th>state: loading</th>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="destructive"
              icon="edit"
              appearance="outline"
              loading
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="destructive"
              icon="edit"
              appearance="fill"
              loading
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="medium"
              type="destructive"
              icon="edit"
              appearance="text"
              loading
            ></sp-button>
          </td>
        </tr>
      </tbody>
    </table>
    <table style="background: #ccc">
      <caption>
        size: large / type: destructive / icon: edit
      </caption>
      <thead>
        <tr>
          <th>appearance</th>
          <th>outline</th>
          <th>fill</th>
          <th>text</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>state: default</th>
          <td>
            <sp-button
              text="text"
              size="large"
              type="destructive"
              icon="edit"
              appearance="outline"
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="large"
              type="destructive"
              icon="edit"
              appearance="fill"
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="large"
              type="destructive"
              icon="edit"
              appearance="text"
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: selected</th>
          <td>
            <sp-button
              text="text"
              size="large"
              type="destructive"
              icon="edit"
              appearance="outline"
              selected
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="large"
              type="destructive"
              icon="edit"
              appearance="fill"
              selected
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="large"
              type="destructive"
              icon="edit"
              appearance="text"
              selected
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: disabled</th>
          <td>
            <sp-button
              text="text"
              size="large"
              type="destructive"
              icon="edit"
              appearance="outline"
              disabled
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="large"
              type="destructive"
              icon="edit"
              appearance="fill"
              disabled
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="large"
              type="destructive"
              icon="edit"
              appearance="text"
              disabled
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: loading</th>
          <td>
            <sp-button
              text="text"
              size="large"
              type="destructive"
              icon="edit"
              appearance="outline"
              loading
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="large"
              type="destructive"
              icon="edit"
              appearance="fill"
              loading
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="large"
              type="destructive"
              icon="edit"
              appearance="text"
              loading
            ></sp-button>
          </td>
        </tr>
      </tbody>
    </table>
    <table style="background: #ccc">
      <caption>
        size: xLarge / type: destructive / icon: edit
      </caption>
      <thead>
        <tr>
          <th>appearance</th>
          <th>outline</th>
          <th>fill</th>
          <th>text</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>state: default</th>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="outline"
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="fill"
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="text"
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: selected</th>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="outline"
              selected
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="fill"
              selected
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="text"
              selected
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: disabled</th>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="outline"
              disabled
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="fill"
              disabled
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="text"
              disabled
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: loading</th>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="outline"
              loading
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="fill"
              loading
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="text"
              loading
            ></sp-button>
          </td>
        </tr>
      </tbody>
    </table>
    <table>
      <caption>
        size: width80 / type: destructive / icon: edit
      </caption>
      <thead>
        <tr>
          <th>appearance</th>
          <th>outline</th>
          <th>fill</th>
          <th>text</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>state: default</th>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="destructive"
              icon="edit"
              appearance="outline"
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="destructive"
              icon="edit"
              appearance="fill"
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="destructive"
              icon="edit"
              appearance="text"
            ></sp-button>
          </td>
        </tr>
        <tr style="background: #ccc">
          <th>state: selected</th>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="destructive"
              icon="edit"
              appearance="outline"
              selected
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="destructive"
              icon="edit"
              appearance="fill"
              selected
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="destructive"
              icon="edit"
              appearance="text"
              selected
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: disabled</th>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="destructive"
              icon="edit"
              appearance="outline"
              disabled
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="destructive"
              icon="edit"
              appearance="fill"
              disabled
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="destructive"
              icon="edit"
              appearance="text"
              disabled
            ></sp-button>
          </td>
        </tr>
        <tr style="background: #ccc">
          <th>state: loading</th>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="destructive"
              icon="edit"
              appearance="outline"
              loading
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="destructive"
              icon="edit"
              appearance="fill"
              loading
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width80"
              type="destructive"
              icon="edit"
              appearance="text"
              loading
            ></sp-button>
          </td>
        </tr>
      </tbody>
    </table>
    <table>
      <caption>
        size: width160 / type: destructive / icon: edit
      </caption>
      <thead>
        <tr>
          <th>appearance</th>
          <th>outline</th>
          <th>fill</th>
          <th>text</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>state: default</th>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="destructive"
              icon="edit"
              appearance="outline"
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="destructive"
              icon="edit"
              appearance="fill"
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="destructive"
              icon="edit"
              appearance="text"
            ></sp-button>
          </td>
        </tr>
        <tr style="background: #ccc">
          <th>state: selected</th>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="destructive"
              icon="edit"
              appearance="outline"
              selected
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="destructive"
              icon="edit"
              appearance="fill"
              selected
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="destructive"
              icon="edit"
              appearance="text"
              selected
            ></sp-button>
          </td>
        </tr>
        <tr>
          <th>state: disabled</th>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="destructive"
              icon="edit"
              appearance="outline"
              disabled
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="destructive"
              icon="edit"
              appearance="fill"
              disabled
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="destructive"
              icon="edit"
              appearance="text"
              disabled
            ></sp-button>
          </td>
        </tr>
        <tr style="background: #ccc">
          <th>state: loading</th>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="destructive"
              icon="edit"
              appearance="outline"
              loading
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="destructive"
              icon="edit"
              appearance="fill"
              loading
            ></sp-button>
          </td>
          <td>
            <sp-button
              text="text"
              size="width160"
              type="destructive"
              icon="edit"
              appearance="text"
              loading
            ></sp-button>
          </td>
        </tr>
      </tbody>
    </table>
  `,
};
