import "../../src/components/button/sp-button";

import type { Meta, StoryObj } from "@storybook/web-components-vite";
import { html } from "lit";
import { action } from "storybook/actions";

import type { SpButton } from "../../src/components/button/sp-button";
import { speedaIconTypes } from "../../src/components/icon/icons";

const meta = {
  component: "sp-button",
  argTypes: {
    slot: { type: "string" },
    icon: {
      control: { type: "select" },
      options: ["", ...speedaIconTypes],
    },
    type: {
      control: { type: "select" },
      options: ["default", "destructive"],
    },
    appearance: {
      control: { type: "select" },
      options: ["outline", "fill", "text"],
    },
    size: {
      control: { type: "select" },
      options: ["medium", "large", "xLarge", "width160", "width80"],
    },
    loading: { type: "boolean" },
    selected: { type: "boolean" },
    disabled: { type: "boolean" },
    onclick: {
      action: "onclick",
    },
  },
  render: (args) => html`
    <sp-button
      icon=${args.icon}
      type=${args.type}
      appearance=${args.appearance}
      size=${args.size}
      ?loading=${args.loading}
      ?selected=${args.selected}
      ?disabled=${args.disabled}
      @click=${args.onclick}
    >
      ${args.slot}
    </sp-button>
  `,
} satisfies Meta<SpButton>;

export default meta;
type Story = StoryObj<SpButton>;

export const Basic: Story = {
  args: {
    slot: "sp-button-text",
    onclick: action("click"),
  },
  tags: ["!dev-only"],
};

export const OverflowWrap: Story = {
  render: () => html`
    <p style="overflow-wrap: break-word;">
      texttexttexttexttexttexttextttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttextexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttext
    </p>
    <sp-button>text</sp-button>
    <sp-button>text</sp-button>
    <sp-button>
      texttexttexttexttexttexttextttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttextexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttext</sp-button
    >
    <sp-button icon="edit">
      texttexttexttexttexttexttextttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttextexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttext
    </sp-button>
    <sp-button>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
      veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
      commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
      velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
      cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
      est laborum.
    </sp-button>
    <sp-button>
      にほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんごにほんご
    </sp-button>
    <div style="display: flex; min-width: 0;">
      <div>サンプルdiv</div>
      <sp-button>
        texttexttexttexttexttexttextttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttextexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttext
      </sp-button>
    </div>
    <div style="display: flex; min-width: 0;">
      <div>サンプルdiv</div>
      <sp-button icon="edit">
        texttexttexttexttexttexttextttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttextexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttexttext
      </sp-button>
    </div>
  `,
};

export const ALL: Story = {
  render: () => html`
    <table>
      <caption>
        size: medium / type: default / icon: edit
      </caption>
      <thead>
        <tr>
          <th>appearance</th>
          <th>outline</th>
          <th>fill</th>
          <th>text</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>state: default</th>
          <td>
            <sp-button
              size="medium"
              type="default"
              icon="edit"
              appearance="outline"
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="medium"
              type="default"
              icon="edit"
              appearance="fill"
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="medium"
              type="default"
              icon="edit"
              appearance="text"
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: selected</th>
          <td>
            <sp-button
              size="medium"
              type="default"
              icon="edit"
              appearance="outline"
              selected
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="medium"
              type="default"
              icon="edit"
              appearance="fill"
              selected
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="medium"
              type="default"
              icon="edit"
              appearance="text"
              selected
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: disabled</th>
          <td>
            <sp-button
              size="medium"
              type="default"
              icon="edit"
              appearance="outline"
              disabled
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="medium"
              type="default"
              icon="edit"
              appearance="fill"
              disabled
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="medium"
              type="default"
              icon="edit"
              appearance="text"
              disabled
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: loading</th>
          <td>
            <sp-button
              size="medium"
              type="default"
              icon="edit"
              appearance="outline"
              loading
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="medium"
              type="default"
              icon="edit"
              appearance="fill"
              loading
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="medium"
              type="default"
              icon="edit"
              appearance="text"
              loading
            >
              text
            </sp-button>
          </td>
        </tr>
      </tbody>
    </table>
    <table>
      <caption>
        size: large / type: default / icon: edit
      </caption>
      <thead>
        <tr>
          <th>appearance</th>
          <th>outline</th>
          <th>fill</th>
          <th>text</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>state: default</th>
          <td>
            <sp-button
              size="large"
              type="default"
              icon="edit"
              appearance="outline"
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="large"
              type="default"
              icon="edit"
              appearance="fill"
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="large"
              type="default"
              icon="edit"
              appearance="text"
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: selected</th>
          <td>
            <sp-button
              size="large"
              type="default"
              icon="edit"
              appearance="outline"
              selected
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="large"
              type="default"
              icon="edit"
              appearance="fill"
              selected
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="large"
              type="default"
              icon="edit"
              appearance="text"
              selected
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: disabled</th>
          <td>
            <sp-button
              size="large"
              type="default"
              icon="edit"
              appearance="outline"
              disabled
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="large"
              type="default"
              icon="edit"
              appearance="fill"
              disabled
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="large"
              type="default"
              icon="edit"
              appearance="text"
              disabled
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: loading</th>
          <td>
            <sp-button
              size="large"
              type="default"
              icon="edit"
              appearance="outline"
              loading
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="large"
              type="default"
              icon="edit"
              appearance="fill"
              loading
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="large"
              type="default"
              icon="edit"
              appearance="text"
              loading
            >
              text
            </sp-button>
          </td>
        </tr>
      </tbody>
    </table>
    <table>
      <caption>
        size: xLarge / type: default / icon: edit
      </caption>
      <thead>
        <tr>
          <th>appearance</th>
          <th>outline</th>
          <th>fill</th>
          <th>text</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>state: default</th>
          <td>
            <sp-button
              size="xLarge"
              type="default"
              icon="edit"
              appearance="outline"
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="xLarge"
              type="default"
              icon="edit"
              appearance="fill"
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="xLarge"
              type="default"
              icon="edit"
              appearance="text"
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: selected</th>
          <td>
            <sp-button
              size="xLarge"
              type="default"
              icon="edit"
              appearance="outline"
              selected
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="xLarge"
              type="default"
              icon="edit"
              appearance="fill"
              selected
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="xLarge"
              type="default"
              icon="edit"
              appearance="text"
              selected
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: disabled</th>
          <td>
            <sp-button
              size="xLarge"
              type="default"
              icon="edit"
              appearance="outline"
              disabled
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="xLarge"
              type="default"
              icon="edit"
              appearance="fill"
              disabled
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="xLarge"
              type="default"
              icon="edit"
              appearance="text"
              disabled
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: loading</th>
          <td>
            <sp-button
              size="xLarge"
              type="default"
              icon="edit"
              appearance="outline"
              loading
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="xLarge"
              type="default"
              icon="edit"
              appearance="fill"
              loading
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="xLarge"
              type="default"
              icon="edit"
              appearance="text"
              loading
            >
              text
            </sp-button>
          </td>
        </tr>
      </tbody>
    </table>
    <table>
      <caption>
        size: width80 / type: default / icon: edit
      </caption>
      <thead>
        <tr>
          <th>appearance</th>
          <th>outline</th>
          <th>fill</th>
          <th>text</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>state: default</th>
          <td>
            <sp-button
              size="width80"
              type="default"
              icon="edit"
              appearance="outline"
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width80"
              type="default"
              icon="edit"
              appearance="fill"
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width80"
              type="default"
              icon="edit"
              appearance="text"
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: selected</th>
          <td>
            <sp-button
              size="width80"
              type="default"
              icon="edit"
              appearance="outline"
              selected
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width80"
              type="default"
              icon="edit"
              appearance="fill"
              selected
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width80"
              type="default"
              icon="edit"
              appearance="text"
              selected
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: disabled</th>
          <td>
            <sp-button
              size="width80"
              type="default"
              icon="edit"
              appearance="outline"
              disabled
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width80"
              type="default"
              icon="edit"
              appearance="fill"
              disabled
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width80"
              type="default"
              icon="edit"
              appearance="text"
              disabled
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: loading</th>
          <td>
            <sp-button
              size="width80"
              type="default"
              icon="edit"
              appearance="outline"
              loading
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width80"
              type="default"
              icon="edit"
              appearance="fill"
              loading
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width80"
              type="default"
              icon="edit"
              appearance="text"
              loading
            >
              text
            </sp-button>
          </td>
        </tr>
      </tbody>
    </table>
    <table>
      <caption>
        size: width160 / type: default / icon: edit
      </caption>
      <thead>
        <tr>
          <th>appearance</th>
          <th>outline</th>
          <th>fill</th>
          <th>text</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>state: default</th>
          <td>
            <sp-button
              size="width160"
              type="default"
              icon="edit"
              appearance="outline"
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width160"
              type="default"
              icon="edit"
              appearance="fill"
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width160"
              type="default"
              icon="edit"
              appearance="text"
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: selected</th>
          <td>
            <sp-button
              size="width160"
              type="default"
              icon="edit"
              appearance="outline"
              selected
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width160"
              type="default"
              icon="edit"
              appearance="fill"
              selected
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width160"
              type="default"
              icon="edit"
              appearance="text"
              selected
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: disabled</th>
          <td>
            <sp-button
              size="width160"
              type="default"
              icon="edit"
              appearance="outline"
              disabled
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width160"
              type="default"
              icon="edit"
              appearance="fill"
              disabled
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width160"
              type="default"
              icon="edit"
              appearance="text"
              disabled
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: loading</th>
          <td>
            <sp-button
              size="width160"
              type="default"
              icon="edit"
              appearance="outline"
              loading
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width160"
              type="default"
              icon="edit"
              appearance="fill"
              loading
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width160"
              type="default"
              icon="edit"
              appearance="text"
              loading
            >
              text
            </sp-button>
          </td>
        </tr>
      </tbody>
    </table>
    <table>
      <caption>
        size: medium / type: destructive / icon: edit
      </caption>
      <thead>
        <tr>
          <th>appearance</th>
          <th>outline</th>
          <th>fill</th>
          <th>text</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>state: default</th>
          <td>
            <sp-button
              size="medium"
              type="destructive"
              icon="edit"
              appearance="outline"
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="medium"
              type="destructive"
              icon="edit"
              appearance="fill"
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="medium"
              type="destructive"
              icon="edit"
              appearance="text"
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr style="background: #ccc">
          <th>state: selected</th>
          <td>
            <sp-button
              size="medium"
              type="destructive"
              icon="edit"
              appearance="outline"
              selected
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="medium"
              type="destructive"
              icon="edit"
              appearance="fill"
              selected
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="medium"
              type="destructive"
              icon="edit"
              appearance="text"
              selected
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: disabled</th>
          <td>
            <sp-button
              size="medium"
              type="destructive"
              icon="edit"
              appearance="outline"
              disabled
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="medium"
              type="destructive"
              icon="edit"
              appearance="fill"
              disabled
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="medium"
              type="destructive"
              icon="edit"
              appearance="text"
              disabled
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr style="background: #ccc">
          <th>state: loading</th>
          <td>
            <sp-button
              size="medium"
              type="destructive"
              icon="edit"
              appearance="outline"
              loading
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="medium"
              type="destructive"
              icon="edit"
              appearance="fill"
              loading
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="medium"
              type="destructive"
              icon="edit"
              appearance="text"
              loading
            >
              text
            </sp-button>
          </td>
        </tr>
      </tbody>
    </table>
    <table style="background: #ccc">
      <caption>
        size: large / type: destructive / icon: edit
      </caption>
      <thead>
        <tr>
          <th>appearance</th>
          <th>outline</th>
          <th>fill</th>
          <th>text</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>state: default</th>
          <td>
            <sp-button
              size="large"
              type="destructive"
              icon="edit"
              appearance="outline"
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="large"
              type="destructive"
              icon="edit"
              appearance="fill"
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="large"
              type="destructive"
              icon="edit"
              appearance="text"
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: selected</th>
          <td>
            <sp-button
              size="large"
              type="destructive"
              icon="edit"
              appearance="outline"
              selected
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="large"
              type="destructive"
              icon="edit"
              appearance="fill"
              selected
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="large"
              type="destructive"
              icon="edit"
              appearance="text"
              selected
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: disabled</th>
          <td>
            <sp-button
              size="large"
              type="destructive"
              icon="edit"
              appearance="outline"
              disabled
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="large"
              type="destructive"
              icon="edit"
              appearance="fill"
              disabled
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="large"
              type="destructive"
              icon="edit"
              appearance="text"
              disabled
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: loading</th>
          <td>
            <sp-button
              size="large"
              type="destructive"
              icon="edit"
              appearance="outline"
              loading
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="large"
              type="destructive"
              icon="edit"
              appearance="fill"
              loading
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="large"
              type="destructive"
              icon="edit"
              appearance="text"
              loading
            >
              text
            </sp-button>
          </td>
        </tr>
      </tbody>
    </table>
    <table style="background: #ccc">
      <caption>
        size: xLarge / type: destructive / icon: edit
      </caption>
      <thead>
        <tr>
          <th>appearance</th>
          <th>outline</th>
          <th>fill</th>
          <th>text</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>state: default</th>
          <td>
            <sp-button
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="outline"
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="fill"
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="text"
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: selected</th>
          <td>
            <sp-button
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="outline"
              selected
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="fill"
              selected
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="text"
              selected
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: disabled</th>
          <td>
            <sp-button
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="outline"
              disabled
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="fill"
              disabled
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="text"
              disabled
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: loading</th>
          <td>
            <sp-button
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="outline"
              loading
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="fill"
              loading
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="xLarge"
              type="destructive"
              icon="edit"
              appearance="text"
              loading
            >
              text
            </sp-button>
          </td>
        </tr>
      </tbody>
    </table>
    <table>
      <caption>
        size: width80 / type: destructive / icon: edit
      </caption>
      <thead>
        <tr>
          <th>appearance</th>
          <th>outline</th>
          <th>fill</th>
          <th>text</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>state: default</th>
          <td>
            <sp-button
              size="width80"
              type="destructive"
              icon="edit"
              appearance="outline"
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width80"
              type="destructive"
              icon="edit"
              appearance="fill"
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width80"
              type="destructive"
              icon="edit"
              appearance="text"
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr style="background: #ccc">
          <th>state: selected</th>
          <td>
            <sp-button
              size="width80"
              type="destructive"
              icon="edit"
              appearance="outline"
              selected
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width80"
              type="destructive"
              icon="edit"
              appearance="fill"
              selected
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width80"
              type="destructive"
              icon="edit"
              appearance="text"
              selected
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: disabled</th>
          <td>
            <sp-button
              size="width80"
              type="destructive"
              icon="edit"
              appearance="outline"
              disabled
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width80"
              type="destructive"
              icon="edit"
              appearance="fill"
              disabled
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width80"
              type="destructive"
              icon="edit"
              appearance="text"
              disabled
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr style="background: #ccc">
          <th>state: loading</th>
          <td>
            <sp-button
              size="width80"
              type="destructive"
              icon="edit"
              appearance="outline"
              loading
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width80"
              type="destructive"
              icon="edit"
              appearance="fill"
              loading
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width80"
              type="destructive"
              icon="edit"
              appearance="text"
              loading
            >
              text
            </sp-button>
          </td>
        </tr>
      </tbody>
    </table>
    <table>
      <caption>
        size: width160 / type: destructive / icon: edit
      </caption>
      <thead>
        <tr>
          <th>appearance</th>
          <th>outline</th>
          <th>fill</th>
          <th>text</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>state: default</th>
          <td>
            <sp-button
              size="width160"
              type="destructive"
              icon="edit"
              appearance="outline"
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width160"
              type="destructive"
              icon="edit"
              appearance="fill"
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width160"
              type="destructive"
              icon="edit"
              appearance="text"
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr style="background: #ccc">
          <th>state: selected</th>
          <td>
            <sp-button
              size="width160"
              type="destructive"
              icon="edit"
              appearance="outline"
              selected
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width160"
              type="destructive"
              icon="edit"
              appearance="fill"
              selected
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width160"
              type="destructive"
              icon="edit"
              appearance="text"
              selected
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr>
          <th>state: disabled</th>
          <td>
            <sp-button
              size="width160"
              type="destructive"
              icon="edit"
              appearance="outline"
              disabled
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width160"
              type="destructive"
              icon="edit"
              appearance="fill"
              disabled
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width160"
              type="destructive"
              icon="edit"
              appearance="text"
              disabled
            >
              text
            </sp-button>
          </td>
        </tr>
        <tr style="background: #ccc">
          <th>state: loading</th>
          <td>
            <sp-button
              size="width160"
              type="destructive"
              icon="edit"
              appearance="outline"
              loading
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width160"
              type="destructive"
              icon="edit"
              appearance="fill"
              loading
            >
              text
            </sp-button>
          </td>
          <td>
            <sp-button
              size="width160"
              type="destructive"
              icon="edit"
              appearance="text"
              loading
            >
              text
            </sp-button>
          </td>
        </tr>
      </tbody>
    </table>
  `,
};
