name: Build

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: git add dist
      - id: check_changes
        run: git diff --staged --quiet || echo "changes_exist=true" >> $GITHUB_OUTPUT
      - if: steps.check_changes.outputs.changes_exist == 'true'
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git commit -m "distディレクトリを更新"
          git push
